# Version de la syntaxe Docker Compose. '3.8' est une version moderne et stable.
# Docker Compose file version. '3.8' is a modern and stable version.
version: '3.8'

# Définition des services (conteneurs) à lancer.
# Definition of the services (containers) to be launched.
services:

  # Service pour la base de données MySQL.
  # Service for the MySQL database.
  db:
    image: mysql:8.0
    container_name: wordpress_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme_root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: changeme_wordpress_password
    networks:
      - wordpress-net

  # Service pour l'application WordPress.
  # Service for the WordPress application.
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_app
    # Le port n'est plus exposé à l'hôte. Nginx gère l'accès externe.
    # The port is no longer exposed to the host. Nginx handles external access.
    restart: always
    volumes:
      # Ce volume est partagé avec Nginx pour servir les fichiers statiques.
      # This volume is shared with Nginx to serve static files.
      - wordpress_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: changeme_wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    networks:
      - wordpress-net

  # Service Nginx agissant comme reverse proxy.
  # Nginx service acting as a reverse proxy.
  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    depends_on:
      - wordpress
    # Mappe le port 80 de l'hôte au port 80 du conteneur Nginx (port HTTP par défaut).
    # Maps port 80 of the host to port 80 of the Nginx container (default HTTP port).
    ports:
      - "82:80"
    volumes:
      # Volume partagé pour les fichiers WordPress (lecture seule).
      # Shared volume for WordPress files (read-only).
      - wordpress_files:/var/www/html:ro
      # Monte le fichier de configuration Nginx que vous allez créer.
      # Mounts the Nginx configuration file you will create.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - wordpress-net

  # Service optionnel mais très utile : phpMyAdmin pour gérer la base de données.
  # Optional but very useful service: phpMyAdmin to manage the database.
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    ports:
      - "8008:80"
    restart: always
    environment:
      PMA_HOST: db
    networks:
      - wordpress-net

# Déclaration des volumes nommés pour la persistance des données.
# Declaration of named volumes for data persistence.
volumes:
  db_data:
  wordpress_files:

# Déclaration du réseau pour permettre aux conteneurs de communiquer entre eux.
# Declaration of the network to allow containers to communicate with each other.
networks:
  wordpress-net:
    driver: bridge
